# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gzc40Fba1zTsOjuNLPm-NmB5xc8HFvu9
"""

# app.py
import streamlit as st
import pandas as pd
import joblib
from sklearn.preprocessing import StandardScaler

# 모델 로드
model = joblib.load("rf_model.pkl")  # 사전에 학습된 모델 파일

# 앱 제목
st.title("심장병 예측기")

# CSV 파일 업로드
uploaded_file = st.file_uploader("CSV 환자 정보 업로드", type="csv")
if uploaded_file:
    # 데이터 불러오기
    df = pd.read_csv(uploaded_file)

    # 'target' 컬럼 제거 (예측용 입력 데이터에는 없어야 함)
    X = df.drop(columns=["target"], errors="ignore")

    # 원-핫 인코딩 (범주형 변수 처리)
    X = pd.get_dummies(X, drop_first=True)

    # 표준화
    scaler = StandardScaler()
    X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)

    # 예측 수행
    prediction = model.predict(X_scaled)

    # 결과 출력
    st.write("예측 결과:", prediction)
    for i, pred in enumerate(prediction):
        st.write(f"환자 {i+1}: {'심장병 있음' if pred == 1 else '심장병 없음'}")